### ISSUE TITLE
Searching with multiple attributes of the same type (i.e. blue and green pills)

### ISSUE THREAD

**Issue by marks** [kgautreaux/pillboxr#1] opened 2014-02-11 17:50 UTC
The way I read the documentation, it seems like the following should work:

`Pillboxr.with(:api_key => "123", :color => [:blue, :green])`

but it doesn't seem to.

**Comment by kgautreaux** [comment] 2014-02-12 06:30
Can you gist the error you are getting or reply with the error so I can see if I can reproduce the issue?

**Comment by marks** [comment] 2014-02-12 13:37
@kgautreaux - yeah, sorry for not including before:

```
2.0.0-p247 :005 > results = Pillboxr.with(:api_key => ENV["PILLBOX_API_KEY"], :color => [:blue,:green])
NameError: uninitialized constant Pillboxr::Pill::Attributes
  from /lib/pillboxr/lib/pillboxr/attributes.rb:56:in `initialize'
  from /lib/pillboxr/lib/pillboxr.rb:68:in `new'
  from /lib/pillboxr/lib/pillboxr.rb:68:in `symbol_to_instance'
  from /lib/pillboxr/lib/pillboxr.rb:27:in `block in with'
  from /lib/pillboxr/lib/pillboxr.rb:25:in `each'
  from /lib/pillboxr/lib/pillboxr.rb:25:in `with'
  from (irb):5
  from /Users/mark/.rvm/rubies/ruby-2.0.0-p247/bin/irb:13:in `<main>'
```

**Comment by kgautreaux** [comment] 2014-02-14 23:22
I pushed my first pass at trying to fix this issue.  See fad78e4b4d.

I'm not closing this yet because I think the Pillbox API ignores all but the last color or shape param in a GET request so I need to write some explicit test cases and ensure that the pills returned are an actual intersection of the multiple searched params or a join of the multiple searched params.

@marks, do you have a specific use case for this functionality because I can tailor the results to your use case?

FYI, when searching multiple colors or shapes use the plural hash key:
`result = Pillboxr.with({:api_key => ENV['API_KEY'], :colors => [:green, :blue]})`

**Comment by marks** [comment] 2014-02-15 01:35
Thanks man- will take a look this weekend. No special use case in particular but personally I think it's better to always return an array but accept just a symbol too. This way a user can iterate over the array instead of always checking the returned objects' parent class. Maybe just personal preference!

Sent from my iPhone

On Feb 14, 2014, at 6:22 PM, "Keith Gautreaux" <notifications@github.com<mailto:notifications@github.com>> wrote:

I pushed my first pass at trying to fix this issue. See fad78e4https://github.com/kgautreaux/pillboxr/commit/fad78e4b4d.

I'm not closing this yet because I think the Pillbox API ignores all but the last color or shape param in a GET request so I need to write some explicit test cases and ensure that the pills returned are an actual intersection of the multiple searched params or a join of the multiple searched params.

@markshttps://github.com/marks, do you have a specific use case for this functionality because I can tailor the results to your use case?

FYI, when searching multiple colors or shapes use the plural hash key:
result = Pillboxr.with({:api_key => ENV['API_KEY'], :colors => [:green, :blue]})

##

**Comment by kgautreaux** [comment] 2014-02-15 02:22
You are right. 'Be conservative in what you send and liberal in what you accept.'  I will change it so it always returns an Array or at least an enumerable object.

**Comment by kgautreaux** [comment] 2014-02-15 06:49
I've made this work for the simple case where you want to find pills that include both colors, i.e. `result = Pillboxr.with({:color => [:blue, :green]})` will return search results populated with pills that include **BOTH** blue **AND** green in their colors (they may include other colors too).

e274e12163 has a few tests too that exercise this functionality.  Since there isn't a specific use case I'm going to close this issue, but if at some point we decide that what we actually want is all pills that have **EITHER** blue **OR** green in their colors we can reopen this issue.

One downside to this change is that `Pillboxr.color(:blue).color(:green).get` doesn't return the same results as the code using `with`.  This isn't easy to fix so I'm not going to attempt it unless someone needs it for their project.

**Closed as completed by kgautreaux** 2014-02-15 06:49 UTC

**Comment by marks** [comment] 2014-02-15 12:47
@kgautreaux much thanks! This works for my use case. I use `with` as opposed to chaining anyway. I agree that in the future an **EITHER/OR** functionality _might_ be requested but honestly think that can be just as well handled by unions/intersections outside the scope of this gem.

Thanks again! I was able to just update my fork and the code that was broken before works perfectly now! I am using this on http://askopendata.com/ if you're interested in trying it out. It only recognizes size, colors, and shapes (for now).

**Comment by kgautreaux** [comment] 2014-02-16 03:16
I checked out your project. Very cool!

I love how you are picking the keywords out of a sentence in the textfield.

I can already see this being very useful for patients and providers. Can't wait to see how it matures.
